//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ITaskWcfService")]
public interface ITaskWcfService
{
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskWcfService/SendEmail", ReplyAction="http://tempuri.org/ITaskWcfService/SendEmailResponse")]
    void SendEmail(string user, string subject, string message);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskWcfService/SendEmail", ReplyAction="http://tempuri.org/ITaskWcfService/SendEmailResponse")]
    System.Threading.Tasks.Task SendEmailAsync(string user, string subject, string message);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskWcfService/SendEmailToAll", ReplyAction="http://tempuri.org/ITaskWcfService/SendEmailToAllResponse")]
    void SendEmailToAll(string subject, string message);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskWcfService/SendEmailToAll", ReplyAction="http://tempuri.org/ITaskWcfService/SendEmailToAllResponse")]
    System.Threading.Tasks.Task SendEmailToAllAsync(string subject, string message);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ITaskWcfServiceChannel : ITaskWcfService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class TaskWcfServiceClient : System.ServiceModel.ClientBase<ITaskWcfService>, ITaskWcfService
{
    
    public TaskWcfServiceClient()
    {
    }
    
    public TaskWcfServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public TaskWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TaskWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TaskWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void SendEmail(string user, string subject, string message)
    {
        base.Channel.SendEmail(user, subject, message);
    }
    
    public System.Threading.Tasks.Task SendEmailAsync(string user, string subject, string message)
    {
        return base.Channel.SendEmailAsync(user, subject, message);
    }
    
    public void SendEmailToAll(string subject, string message)
    {
        base.Channel.SendEmailToAll(subject, message);
    }
    
    public System.Threading.Tasks.Task SendEmailToAllAsync(string subject, string message)
    {
        return base.Channel.SendEmailToAllAsync(subject, message);
    }
}
