//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestControlTool.Core.Implementations.SqlCEModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AccountsEntities : DbContext
    {
        public AccountsEntities()
            : base("name=AccountsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccountModel> Accounts { get; set; }
        public DbSet<HyperVMachineModel> HyperVMachines { get; set; }
        public DbSet<ServerModel> Servers { get; set; }
        public DbSet<TaskModel> Tasks { get; set; }
        public DbSet<VCenterMachineModel> VCenterMachines { get; set; }
    }
}
