//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestControlTool.Core.Implementations.SqlCEModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskModel
    {
        public string Id { get; set; }
        public DateTime StartTime { get; set; }
        public string Frequency { get; set; }
        public DateTime EndTime { get; set; }
        public bool IsEnabled { get; set; }
        public string Owner { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public DateTime LastRun { get; set; }
    
        public virtual AccountModel Account { get; set; }
    }
}
