//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ITaskWcfService")]
public interface ITaskWcfService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskWcfService/StartTask", ReplyAction="http://tempuri.org/ITaskWcfService/StartTaskResponse")]
    bool StartTask(System.Guid id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskWcfService/StartTask", ReplyAction="http://tempuri.org/ITaskWcfService/StartTaskResponse")]
    System.Threading.Tasks.Task<bool> StartTaskAsync(System.Guid id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskWcfService/StopTask", ReplyAction="http://tempuri.org/ITaskWcfService/StopTaskResponse")]
    bool StopTask(System.Guid id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskWcfService/StopTask", ReplyAction="http://tempuri.org/ITaskWcfService/StopTaskResponse")]
    System.Threading.Tasks.Task<bool> StopTaskAsync(System.Guid id);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ITaskWcfServiceChannel : ITaskWcfService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class TaskWcfServiceClient : System.ServiceModel.ClientBase<ITaskWcfService>, ITaskWcfService
{
    
    public TaskWcfServiceClient()
    {
    }
    
    public TaskWcfServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public TaskWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TaskWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TaskWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool StartTask(System.Guid id)
    {
        return base.Channel.StartTask(id);
    }
    
    public System.Threading.Tasks.Task<bool> StartTaskAsync(System.Guid id)
    {
        return base.Channel.StartTaskAsync(id);
    }
    
    public bool StopTask(System.Guid id)
    {
        return base.Channel.StopTask(id);
    }
    
    public System.Threading.Tasks.Task<bool> StopTaskAsync(System.Guid id)
    {
        return base.Channel.StopTaskAsync(id);
    }
}
